spring:
  application:
    name: "auth-service"

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

JWT_PRIVATE_SECRET: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCp+eLfsgrOiQ+RGMvp6TIaDAeIZycsgAeGChZ13KtpJHE3DhV8E1IVRovFP0MyI0LAfrXgAtqxXpY0nC2I9fA9VNvxTp8B0oBJ0rTN32NlpB4afZ5T67nnaDbY6KatAa6qu5O/Xo0ukR25OI8rjMz5EubyMKqFmJmHCaIV8LJyI+EF9icFhDv6luV0Ri3DTvaZfdRm7MI0200X8gOeSiPixwDTgwyaaG2M3gX6nK53iOSyeuZpHygm8LeWwumUvuaKchpwaWR8EDrCp9rePPwR8S2AFjBanpT/KgdND/2a3luH8QfDEsiOzhzDruRFxOes5C0fg3u4ChaJf0Sq8hXbAgMBAAECggEASr2kCqv9v4KaMzmdlJ3jV3u5pjuBiLpFVKXD6ZCeWM3a8JQDU3slaVCLbjDaqcXCeOVesQFgS4TldH3GMga+3CEf03Q4S/NVUODTewFC8jMfv5NEFu+836m+EFQA0ms+dDmmBoybdQH/eW4K2mH/0XgD0DQhDzyiKbRNLuuXc8NlnF/9op4Cu+RQ7Q1O4ueEVTQy1WoN59fQPDgjvjhkKZn08keA4O69tK6KFc4KGSudT2W8iE6d9qqnMt+FqSwwgGOttZfnKii7KIaxdEbQ/6oZOENbo3LN1vols71ccmiLzEjw2JiELIK0wGnEXHGwLNQG/sKVobkWRIyFl85akQKBgQDnuTEab01/HgfKjFjsamKxx28ACw/jAONhiEEDWlsQVjjoOnXzKD6EipvAOGb1+M4SpXRlAsjMIS1QpkZ0VNZn+OIuMHOFekBhCJONsOp3mZ5lX4ss5kIKSXoTnSCirTUPmzOd/S9ElQPVCR77/9+69s0clNel5uVUGhPbpd4DCwKBgQC7yKLCQNHpVCgxBKUgVZw41tUgYNjwJ1NF2S5jLOb5xOt06t03SmVMrqm9luSRAGncadJq8SCSbChmU4Ird1DbKjt2Ua+6rpMUhRzg77jIIZxZ9bFcJibY8tUebBrCHdmRULHfUs8LqphLfoppEqjEDyZVHF09T7RqHmmy6y76cQKBgQDTJEe90pVGstJemSudoAJ2A0b9PxcmvPRzNngm2foIFMidskcvXQg6NSJeMAaBMkhzbRd1wue8OK7VweyIq5UCACH3/GYGxbJLuEja3s2GVQ+jRz/FlbmvLexyWsYV9MVYhw6tcrnTQATR5RG6hRgTgDa9SFKG9LEZxPk7NxPoqQKBgBMpCqplcMWtB5jQz4R4F8OY8BAosZn3eUC0Q05tQ3gSxq+cU0wT9DgZzkoA/ntpHmQWDBlLVzZ5gLnIJY0H1KE4Mu8EsLiMnYdHecXdz+3juA9ZyWoMnoQeau56u1Q5NXzlTfDqgyO+mWGCnN7Rv5SZsyCWD1F1M4Rsa/6MjrORAoGBAK6b2uD1Ua6Tw4F41bOmTwl/H6CuzFG/qibv4y9AuIYOIZlkQVaJIRWp60KiPkrH4F61d/H01yoCVc71UAeD8/DDu2cJ5CWMttBjAhzHg+LAtJOdXW+i+mlhSnYM4pKSkvAkK+sfkP+P9xLxXr2pYgb4FGXpSRvl/VWSxnzS3BcX"