services:
  # Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - food-delivery-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - food-delivery-network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/food-delivery-user-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - food-delivery-network

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - restaurant-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://restaurant-db:3306/food-delivery-restaurant-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - food-delivery-network

  # Order Service
  order-service:
    build: ./order-service
    ports:
      - "9003:9003"
    depends_on:
      - eureka-server
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://order-db:3306/food-delivery-order-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - food-delivery-network

  # Payment Service
  payment-service:
    build: ./payment-service
    ports:
      - "9004:9004"
    depends_on:
      - eureka-server
      - payment-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://payment-db:3306/food-delivery-payment-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - food-delivery-network

  # Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_PRIVATE_SECRET=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCp+eLfsgrOiQ+RGMvp6TIaDAeIZycsgAeGChZ13KtpJHE3DhV8E1IVRovFP0MyI0LAfrXgAtqxXpY0nC2I9fA9VNvxTp8B0oBJ0rTN32NlpB4afZ5T67nnaDbY6KatAa6qu5O/Xo0ukR25OI8rjMz5EubyMKqFmJmHCaIV8LJyI+EF9icFhDv6luV0Ri3DTvaZfdRm7MI0200X8gOeSiPixwDTgwyaaG2M3gX6nK53iOSyeuZpHygm8LeWwumUvuaKchpwaWR8EDrCp9rePPwR8S2AFjBanpT/KgdND/2a3luH8QfDEsiOzhzDruRFxOes5C0fg3u4ChaJf0Sq8hXbAgMBAAECggEASr2kCqv9v4KaMzmdlJ3jV3u5pjuBiLpFVKXD6ZCeWM3a8JQDU3slaVCLbjDaqcXCeOVesQFgS4TldH3GMga+3CEf03Q4S/NVUODTewFC8jMfv5NEFu+836m+EFQA0ms+dDmmBoybdQH/eW4K2mH/0XgD0DQhDzyiKbRNLuuXc8NlnF/9op4Cu+RQ7Q1O4ueEVTQy1WoN59fQPDgjvjhkKZn08keA4O69tK6KFc4KGSudT2W8iE6d9qqnMt+FqSwwgGOttZfnKii7KIaxdEbQ/6oZOENbo3LN1vols71ccmiLzEjw2JiELIK0wGnEXHGwLNQG/sKVobkWRIyFl85akQKBgQDnuTEab01/HgfKjFjsamKxx28ACw/jAONhiEEDWlsQVjjoOnXzKD6EipvAOGb1+M4SpXRlAsjMIS1QpkZ0VNZn+OIuMHOFekBhCJONsOp3mZ5lX4ss5kIKSXoTnSCirTUPmzOd/S9ElQPVCR77/9+69s0clNel5uVUGhPbpd4DCwKBgQC7yKLCQNHpVCgxBKUgVZw41tUgYNjwJ1NF2S5jLOb5xOt06t03SmVMrqm9luSRAGncadJq8SCSbChmU4Ird1DbKjt2Ua+6rpMUhRzg77jIIZxZ9bFcJibY8tUebBrCHdmRULHfUs8LqphLfoppEqjEDyZVHF09T7RqHmmy6y76cQKBgQDTJEe90pVGstJemSudoAJ2A0b9PxcmvPRzNngm2foIFMidskcvXQg6NSJeMAaBMkhzbRd1wue8OK7VweyIq5UCACH3/GYGxbJLuEja3s2GVQ+jRz/FlbmvLexyWsYV9MVYhw6tcrnTQATR5RG6hRgTgDa9SFKG9LEZxPk7NxPoqQKBgBMpCqplcMWtB5jQz4R4F8OY8BAosZn3eUC0Q05tQ3gSxq+cU0wT9DgZzkoA/ntpHmQWDBlLVzZ5gLnIJY0H1KE4Mu8EsLiMnYdHecXdz+3juA9ZyWoMnoQeau56u1Q5NXzlTfDqgyO+mWGCnN7Rv5SZsyCWD1F1M4Rsa/6MjrORAoGBAK6b2uD1Ua6Tw4F41bOmTwl/H6CuzFG/qibv4y9AuIYOIZlkQVaJIRWp60KiPkrH4F61d/H01yoCVc71UAeD8/DDu2cJ5CWMttBjAhzHg+LAtJOdXW+i+mlhSnYM4pKSkvAkK+sfkP+P9xLxXr2pYgb4FGXpSRvl/VWSxnzS3BcX
    networks:
      - food-delivery-network

  # Databases
  user-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=food-delivery-user-db
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - food-delivery-network

  restaurant-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=food-delivery-restaurant-db
    volumes:
      - restaurant-db-data:/var/lib/mysql
    networks:
      - food-delivery-network

  order-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=food-delivery-order-db
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - food-delivery-network

  payment-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=food-delivery-payment-db
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge

volumes:
  user-db-data:
  restaurant-db-data:
  order-db-data:
  payment-db-data: