spring:
  application:
    name: "user-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/food-delivery-user-db"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}