spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: "api-gateway"
  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1

#        - id: airport-service
#          uri: lb://airport-service
#          predicates:
#            - Path=/airport-service/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: yourServiceCircuitBreaker
#                fallbackUri: forward:/health/airport-service

#        - id: flight-service
#          uri: lb://flight-service
#          predicates:
#            - Path=/flight-service/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: yourServiceCircuitBreaker
#                fallbackUri: forward:/health/flight-service

#        - id: schedule-service
#          uri: lb://schedule-service
#          predicates:
#            - Path=/schedule-service/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: yourServiceCircuitBreaker
#                fallbackUri: forward:/health/schedule-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    instances:
      yourServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

JWT_PUBLIC_SECRET: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqfni37IKzokPkRjL6ekyGgwHiGcnLIAHhgoWddyraSRxNw4VfBNSFUaLxT9DMiNCwH614ALasV6WNJwtiPXwPVTb8U6fAdKASdK0zd9jZaQeGn2eU+u552g22OimrQGuqruTv16NLpEduTiPK4zM+RLm8jCqhZiZhwmiFfCyciPhBfYnBYQ7+pbldEYtw072mX3UZuzCNNtNF/IDnkoj4scA04MMmmhtjN4F+pyud4jksnrmaR8oJvC3lsLplL7minIacGlkfBA6wqfa3jz8EfEtgBYwWp6U/yoHTQ/9mt5bh/EHwxLIjs4cw67kRcTnrOQtH4N7uAoWiX9EqvIV2wIDAQAB"