spring:
  application:
    name: "restaurant-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/food-delivery-restaurant-db"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    preferIpAddress: true
    hostname: "localhost"
    instance-id: "${spring.application.name}:${server.port}"
